### ISSUE TITLE
Does not build on Qt >= 5.8

### ISSUE THREAD

**Issue by oxy** [liri-archive/wayland-archived#15]
Qt5PlatformSupport is deprecated, and various other blocking issues.

The cMake one can be fixed via:
https://cgit.kde.org/kwin.git/commit/?id=052fa2e4ee329810f62c29e546254fb45bf8a375

Otherwise I've no idea.

**Comment by plfiorini** [comment]
The `develop` branch builds with Qt 5.8

**Comment by oxy** [comment]
Thanks. Will try

**Comment by oxy** [comment]
Can confirm it builds on develop. The pkgbuild on AUar still says greenisland-git tho. I'll mark this issue closed.
