### ISSUE TITLE
fullscreen shell integration

### ISSUE THREAD

**Issue by plfiorini** [liri-archive/wayland-archived#2]
Implement a fullscreen shell integration for the wayland QPA plugin in order to replace the EGL device integration for the liri QPA plugin.

The reason is that a shell integration extends the wayland QPA plugin that has all the groundwork done for us, while the EGL device integration requires writing everything from scratch and that has proven to be difficult.

**Comment by n3rdopolis** [comment]
It works!

**Comment by plfiorini** [comment]
Finally all the pieces are coming together!
