### ISSUE TITLE
Build failure with Qt 5.10

### ISSUE THREAD

**Issue by SolarAquarion** [liri-archive/wayland-archived#32]
ERROR: /usr/bin/g++ -g -O0 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII '-DLIRIWAYLAND_VERSION="0.9.0.1"' -DQT_BUILD_LIRILIBINPUT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -I/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1 -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1/LiriLibInput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1/LiriLibInput/private -I/usr/include -I/usr/include/LiriLogind -I/usr/include/LiriLogind/0.9.0.1 -I/usr/include/LiriLogind/0.9.0.1/LiriLogind -I/usr/include/LiriLogind/0.9.0.1/LiriLogind/private -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/LiriLibInput.24883f86/qt.headers -I/usr/include/qt/QtCore/5.10.0 -I/usr/include/qt/QtCore/5.10.0/QtCore -I/usr/include/qt/QtDBus -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1 -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1/LiriUDev -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1/LiriUDev/private -I/usr/include/qt/QtGui -I/usr/include/qt/QtGui/5.10.0 -I/usr/include/qt/QtGui/5.10.0/QtGui -I/home/solaraquarion/build/liri-wayland-git/src/wayland/src/eglfsxkb -std=c++0x -o /home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/LiriLibInput.24883f86/.obj/3a52ce780950d4d9/libinputgesture.cpp.o -c /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp

ERROR: /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchBegin(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:51:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchEnd(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:61:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchUpdate(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:74:32: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEventWithRealValue(std::nullptr_t, const quint64&, Qt::NativeGestureType, const double&, QPointF&, QPointF&)’
                 scale, pos, pos);
                                ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note: candidate: static void QWindowSystemInterface::handleGestureEventWithRealValue(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, qreal, QPointF&, QPointF&)
     static void handleGestureEventWithRealValue(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note:   candidate expects 7 arguments, 6 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:78:36: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEventWithRealValue(std::nullptr_t, const quint64&, Qt::NativeGestureType, const double&, QPointF&, QPointF&)’
                     angle, pos, pos);
                                    ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note: candidate: static void QWindowSystemInterface::handleGestureEventWithRealValue(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, qreal, QPointF&, QPointF&)
     static void handleGestureEventWithRealValue(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note:   candidate expects 7 arguments, 6 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeBegin(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:88:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeEnd(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:98:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeUpdate(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:109:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
ERROR: Process failed with exit code 1.
The following products could not be built for configuration default:
	LiriWaylandClient-qbs
	LiriWaylandClient-pkgconfig
	LiriWaylandClient-cmake
	LiriWaylandClientHeaders
	LiriWaylandClient
	LiriEglFS-qbs
	LiriEglFS-pkgconfig
	LiriEglFS
	LiriLibInput-qbs
	LiriLibInput-pkgconfig
	LiriLibInput
	LiriWaylandServer-qbs
	LiriWaylandServer-pkgconfig
	LiriWaylandServer
	LiriUDev-qbs
	LiriUDev-pkgconfig
	liriwaylandserverplugin
	liriwaylandserverprivateplugin
	lirixwaylandplugin
	materialdecorationplugin
	kms
	lirieglfs
	fullscreen-shell
	tst_wl_libinput
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by SolarAquarion** [comment]
RROR: /usr/bin/g++ -g -O0 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII '-DLIRIWAYLAND_VERSION="0.9.0.1"' -DQT_BUILD_LIRILIBINPUT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -I/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1 -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1/LiriLibInput -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriLibInput/0.9.0.1/LiriLibInput/private -I/usr/include -I/usr/include/LiriLogind -I/usr/include/LiriLogind/0.9.0 -I/usr/include/LiriLogind/0.9.0/LiriLogind -I/usr/include/LiriLogind/0.9.0/LiriLogind/private -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/LiriLibInput.24883f86/qt.headers -I/usr/include/qt/QtDBus -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1 -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1/LiriUDev -I/home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/include/LiriUDev/0.9.0.1/LiriUDev/private -I/usr/include/qt/QtCore/5.10.0 -I/usr/include/qt/QtCore/5.10.0/QtCore -I/usr/include/qt/QtGui -I/usr/include/qt/QtGui/5.10.0 -I/usr/include/qt/QtGui/5.10.0/QtGui -I/home/solaraquarion/build/liri-wayland-git/src/wayland/src/eglfsxkb -std=c++0x -o /home/solaraquarion/build/liri-wayland-git/src/wayland/build/default/LiriLibInput.24883f86/.obj/3a52ce780950d4d9/libinputgesture.cpp.o -c /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp

ERROR: /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchBegin(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:51:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchEnd(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:61:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handlePinchUpdate(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:74:32: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEventWithRealValue(std::nullptr_t, const quint64&, Qt::NativeGestureType, const double&, QPointF&, QPointF&)’
                 scale, pos, pos);
                                ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note: candidate: static void QWindowSystemInterface::handleGestureEventWithRealValue(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, qreal, QPointF&, QPointF&)
     static void handleGestureEventWithRealValue(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note:   candidate expects 7 arguments, 6 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:78:36: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEventWithRealValue(std::nullptr_t, const quint64&, Qt::NativeGestureType, const double&, QPointF&, QPointF&)’
                     angle, pos, pos);
                                    ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note: candidate: static void QWindowSystemInterface::handleGestureEventWithRealValue(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, qreal, QPointF&, QPointF&)
     static void handleGestureEventWithRealValue(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:230:17: note:   candidate expects 7 arguments, 6 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeBegin(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:88:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeEnd(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:98:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp: In member function ‘void Liri::Platform::LibInputGesture::handleSwipeUpdate(libinput_event_gesture*)’:
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:109:25: error: no matching function for call to ‘QWindowSystemInterface::handleGestureEvent(std::nullptr_t, const quint64&, Qt::NativeGestureType, QPointF&, QPointF&)’
                 pos, pos);
                         ^
In file included from /home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinputgesture.cpp:28:0:
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note: candidate: static void QWindowSystemInterface::handleGestureEvent(QWindow*, QTouchDevice*, ulong, Qt::NativeGestureType, QPointF&, QPointF&)
     static void handleGestureEvent(QWindow *window, QTouchDevice *device,  ulong timestamp, Qt::NativeGestureType type,
                 ^~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/5.10.0/QtGui/qpa/qwindowsysteminterface.h:228:17: note:   candidate expects 6 arguments, 5 provided
ERROR: Process failed with exit code 1.
The following products could not be built for configuration default:
        LiriWaylandClient-qbs
        LiriWaylandClient-pkgconfig
        LiriWaylandClient-cmake
        LiriWaylandClientHeaders
        LiriWaylandClient
        LiriEglFS-qbs
        LiriEglFS-pkgconfig
        LiriEglFSHeaders
        LiriEglFS
        LiriLibInput-qbs
        LiriLibInput-pkgconfig
        LiriLibInput
        LiriWaylandServer-qbs
        LiriWaylandServer-pkgconfig
        LiriWaylandServer
        LiriUDev-qbs
        liriwaylandserverplugin
        liriwaylandserverprivateplugin
        lirixwaylandplugin
        materialdecorationplugin
        kms
        lirieglfs
        fullscreen-shell
        tst_wl_libinput
==> ERROR: A failure occurred in build().

**Comment by plfiorini** [comment]
@SolarAquarion Build fixed, I'm waiting for the CI to complete. Beware the Arch Linux package qt5-base should depend on vulkan-headers but it doesn't. This might lead to build issues with other stuff like https://github.com/liri/browser
