### ISSUE TITLE
Creating a wayland compositor for raspberry pi

### ISSUE THREAD

**Issue by dmsmdms** [liri-archive/wayland-archived#33]
Hello. I have a raspberry pi and I want to create my own compositor for him. I have already created what I need using Qt Wayland Compositor, but it does not support GTK and XWayland. Is it possible to use Liri Wayland in such case?

**Comment by plfiorini** [comment]
GTK+ support is available in Qt 5.10 (that is xdg_shell v6, the last unstable version), and for XWayland you can use the `Liri.XWayland` QML plugin in this repository.

**Comment by dmsmdms** [comment]
Ok, but how can I use the Liri.XWayland? Is there any documentation?

**Comment by plfiorini** [comment]
No documentation yet, you need to read the code at the moment.
