### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [liri-archive/wayland-archived#37]
Fetching origin
==> Validating source files with md5sums...
    wayland ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of wayland git repo...
Cloning into 'wayland'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Profile 'gcc' created for '/usr/bin/g++'.
Creating profile 'qt5'.
Setting profile 'gcc' as the base profile for this profile.
Skipping prl file '/usr/lib/libQt5dtkwidget.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5AV.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5WebKit.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5AVWidgets.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5Fluid.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5WebKitWidgets.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5dtkcore.prl', because it cannot be opened (No such file or directory).
Build graph does not yet exist for configuration 'default'. Starting from scratch.
Resolving project for configuration default
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
SOFT ASSERT: varValue in language/evaluatorscriptclass.cpp:597
ERROR: /usr/share/qbs/imports/LiriModuleProject.qbs:86:5 Error while handling product 'LiriEglFSKmsSupport-pkgconfig':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSKmsSupport-pkgconfig'.
/usr/share/qbs/imports/LiriModuleProject.qbs:86:5 Error while handling product 'LiriEglFSDeviceIntegration-pkgconfig':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSDeviceIntegration-pkgconfig'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/eglfs_kms.qbs:3:1 Error while handling product 'eglfs-kms-integration':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'eglfs-kms-integration'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/plugins/platforms/eglfs/eglfs-plugin.qbs:3:1 Error while handling product 'lirieglfs':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'lirieglfs'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:44:5 Error while handling product 'LiriLibInput':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:57:9 Dependency 'LiriLogind' not found for product 'LiriLibInput'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms_support/eglfs_kms_support.qbs:27:5 Error while handling product 'LiriEglFSKmsSupport':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSKmsSupport'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/plugins/platforms/eglfs/eglfsdeviceintegration.qbs:32:5 Error while handling product 'LiriEglFSDeviceIntegration':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSDeviceIntegration'.
/usr/share/qbs/imports/LiriModuleProject.qbs:149:5 Error while handling product 'LiriLibInput-cmake':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriLibInput-cmake'.
/usr/share/qbs/imports/LiriModuleProject.qbs:149:5 Error while handling product 'LiriEglFSKmsSupport-cmake':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSKmsSupport-cmake'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/tests/manual/libinput/libinput.qbs:3:1 Error while handling product 'tst_wl_libinput':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'tst_wl_libinput'.
/usr/share/qbs/imports/LiriModuleProject.qbs:149:5 Error while handling product 'LiriEglFSDeviceIntegration-cmake':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriEglFSDeviceIntegration-cmake'.
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms_egldevice/eglfs_kms_egldevice.qbs:3:1 Error while handling product 'eglfs-kms-egldevice-integration':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'eglfs-kms-egldevice-integration'.
/usr/share/qbs/imports/LiriModuleProject.qbs:86:5 Error while handling product 'LiriLibInput-pkgconfig':
/home/solaraquarion/build/liri-wayland-git/src/wayland/src/libinput/libinput.qbs:82:13 Dependency 'LiriLogind' not found for product 'LiriLibInput-pkgconfig'.

**Comment by plfiorini** [comment]
There was a build issue that was fixed although this one seems different.
Anyway Docker builds are fine.
