### ISSUE TITLE
Ubuntu Wayland

### ISSUE THREAD

**Issue by ghost** [liri-archive/wayland-archived#44]
For years we met and suggested to join but well I just commented to contextualize, now we are developing our own desktop environments and I would like to know if Ubuntu, Devuan and Debian can be used this project and what would be the dependencies?

**Comment by plfiorini** [comment]
Let me check if I understand your question: you are developing your own desktop environment but you don't know if Ubuntu, Devuan or Debian has the right dependencies to do so?

**Comment by plfiorini** [comment]
How is this question related to Liri?

**Comment by plfiorini** [comment]
No reply for 16 days, closing the issue.

**Comment by ghost** [comment]
Hi @plfiorini sorry I back how are you? We development desktop in Devuan.
